#!/usr/bin/python3
import rclpy
from raubase_ros.interface import ImageProcessorInterface
from dtu_robocup_24.image import ArUcoProcessor, BallDetector, BallDetectorLearned


class ImageProcessor(ImageProcessorInterface):
    """
    Image processor for the DTU RoboCup24
    """

    def __init__(self) -> None:
        super().__init__("ImageProcessor")  # type: ignore

        self.get_logger().info("Loading processing units")
        self.attach_processing_unit(ArUcoProcessor())
        self.attach_processing_unit(BallDetector())
        self.attach_processing_unit(BallDetectorLearned())
        self.get_logger().info("Done!")


# =============================================================================
# ROS Launching
# =============================================================================


def main(args=None):
    rclpy.init(args=args)

    ArUcoProcessor()

    proc = ImageProcessor()

    while rclpy.ok():
        rclpy.spin_once(proc)

    proc.destroy_node()
    rclpy.shutdown()


if __name__ == "__main__":
    main()
