#!/usr/bin/python3
import rclpy
from raubase_ros.interface import ImageProcessor as proc_interface
from dtu_robocup_24.image import ArUcoProcessor, MLObjectProcessor


class ImageProcessor(proc_interface):
    """
    Image processor for the DTU RoboCup24
    """

    def __init__(self) -> None:
        super().__init__("ImageProcessor")

        self.get_logger().info("Loading processing units")
        self.attach_processing_unit(ArUcoProcessor())
        self.attach_processing_unit(MLObjectProcessor())
        self.get_logger().info("Done!")


# =============================================================================
# ROS Launching
# =============================================================================


def main(args=None):
    rclpy.init(args=args)

    proc = ImageProcessor()

    while rclpy.ok():
        rclpy.spin_once(proc)

    proc.destroy_node()
    rclpy.shutdown()


if __name__ == "__main__":
    main()
