#!/usr/bin/python3
import warnings
from raubase_ros.plan import BehaviourPlan
from rclpy import init, ok, spin_once, shutdown

from dtu_robocup_24.plans import (
    SeeSawTask,
    MinigolfTask,
    RampTask,
    AxeGateTask,
    PackageDelivery,
    StartTask,
)


warnings.simplefilter("ignore", UserWarning)


class DTURobocup24Plan(BehaviourPlan):
    def __init__(self) -> None:
        super().__init__(require_user_input=False)

        self.add_task(StartTask())
        self.add_task(RampTask())
        self.add_task(MinigolfTask())
        self.add_task(PackageDelivery())
        #self.add_task(ThreeGateTask())
        self.add_task(AxeGateTask())
        #self.add_task(TunnelTask())
        #self.add_task(RaceTrackTask())
        #self.add_task(SeeSawTask())
        #self.add_task(SirenTask())


if __name__ == "__main__":
    init()
    node = DTURobocup24Plan()

    while ok():
        spin_once(node)

    shutdown()
